
stages:
  - test
  - build
  - deploy

linux_build:
    stage: build
    image: ubuntu:14.04
    before_script:
      - apt-get update
      - apt-get install -y git cmake build-essential autoconf libtool pkg-config libssl-dev
      - git submodule update --init --recursive

    script: # Modify the commands below to build your repository.
      # curl
      - cd 3d-party/curl
      - ./buildconf
      - ./configure
      - make
      - make install
      - cd ../..
      
      # appUpdater
      - mkdir out
      - cd out
      - cmake ../
      - cd ..
      - cmake --build out --config Release
     
      # ctest
      - cd out
      - ctest -j10 -C Release -T test --output-on-failure
      - cd ..

      # prepare artifacts
      - cp out/src/*appUpdaterShared.* ./
      - cp out/src/*appUpdaterStatic.* ./
      - cp src/updater.h ./
    artifacts:
        name: linux_release
        paths:
          - ./*appUpdaterShared.*
          - ./*appUpdaterStatic.*
          - ./updater.h
        expire_in: 3 day
     
linux_deploy:
    variables:
      LINUX_ARTIFACT_URL: "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/download?job=linux_build"
      RELEASES_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases"
      RELEASES_ASSETS_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"
    stage: deploy
    only:
      - tags
    script:
      - apt-get update
      - apt-get install -y curl
      - echo "$LINUX_ARTIFACT_URL | $RELEASES_URL | $RELEASES_ASSETS_URL"     
      - 'curl -X POST -H "PRIVATE-TOKEN: $fullAccessToken" -d name=$CI_COMMIT_TAG -d url="$LINUX_ARTIFACT_URL" --url "$RELEASES_URL"'
      - 'curl -X POST -H "PRIVATE-TOKEN: $fullAccessToken" -d name="linux" -d url="$LINUX_ARTIFACT_URL" --url "$RELEASES_ASSETS_URL"'